### ISSUE TITLE
Unable to start MQTT exporter

### ISSUE THREAD

**Issue by johsk** [tess1o/go-ecoflow-exporter#15]
Hi,
iam getting 
"ERROR Unable to start mqtt exporter error="either ECOFLOW_DEVICES_PRETTY_NAMES or ECOFLOW_DEVICES must be provided"

my .env looks like this (XXX means cut the content):

ECOFLOW_DEVICES=R331XXX
ECOFLOW_EMAIL=aXXX@gmx.de
ECOFLOW_PASSWORD=wozXXX

i followed go-ecoflow-exporter/docs/prometheus.md

and i pulled e4968ba9bbfa52670a91b8129cb3f6ab8c7061c1

**Comment by johsk** [comment]
I think returning here prematurely is the problem

https://github.com/tess1o/go-ecoflow-exporter/blob/e4968ba9bbfa52670a91b8129cb3f6ab8c7061c1/main.go#L152

or it does not get the ENV variable properly and thus beeing empty string.

IDK

**Comment by tess1o** [comment]
Hello,

Yes, looks like that return statement is incorrect. It ignores the value of `ECOFLOW_DEVICES` if  `ECOFLOW_DEVICES_PRETTY_NAMES ` is not provided. I will fix the issue today or tomorrow.

**Comment by tess1o** [comment]
Hello,

The fix is available in the latest version (1.4.0). I've fixed the gap when `ECOFLOW_DEVICES` is provided and `ECOFLOW_DEVICES_PRETTY_NAMES` is not. 

Please note that MQTT version of the exporter is impacted with the same behaviour as described here: https://github.com/berezhinskiy/ecoflow_exporter/issues/67

The "rest" version of this exporter works just fine (`EXPORTER_TYPE=rest`). You can find details how to configure it in the same docs (it requires getting developer's access token and secret token from the Ecoflow website).

**Comment by johsk** [comment]
Hi, 
iam very sorry, but i still get

`ERROR Unable to start mqtt exporter error=either ECOFLOW_DEVICES_PRETTY_NAMES or ECOFLOW_DEVICES must be provided`

my .env looks likes this:

```
#possible values: mqtt or rest. Default is rest
EXPORTER_TYPE=mqtt

# If EXPORTER_TYPE=rest (or it's blank), then the following parameters are mandatory:
ECOFLOW_ACCESS_KEY=YOUR_ECOFLOW_ACCESS_KEY
ECOFLOW_SECRET_KEY=YOUR_ECOFLOW_SECRET_KEY

### If EXPORTER_TYPE=mqtt, then the following parameters are mandatory:
ECOFLOW_EMAIL=aXXX@gmx.de
ECOFLOW_PASSWORD=wXXX

ECOFLOW_DEVICES=R331XXX
#OR
#ECOFLOW_DEVICES_PRETTY_NAMES='{"SN1":"My Cool Ecoflow device"}'
```

Update:
Sorry I did not do a `docker-compose pull`. Seems like the old version was still in cache.

**Comment by tess1o** [comment]
I assume it works with the new version. Can you please confirm?
